### ISSUE TITLE
[Feature Request] Mac OS Support

### ISSUE THREAD

**Issue by tidusjar** [MattJeanes/Abyss-Infrastructure#1]
Please add dat MacOS support

**Comment by MattJeanes** [comment]
This isn't even an app that runs on anything

**Comment by Legend-etf** [comment]
Its been nearly 3 years. Just wondering if there is going to be a re-evaluation of maybe adding this feature. Thanks.

**Comment by MattJeanes** [comment]
There will not. Thanks for your comment
